// Conteúdo pedagógico da V1. Para adicionar um card, inclua { front, back } no baralho.
window.FLASHCARD_DECKS = [
  {
    id: "cifras-basicas",
    title: "Cifras Básicas",
    description: "Associe C, D, E, F, G, A e B às notas musicais.",
    cards: [
      { front: "C", back: "Dó" },
      { front: "D", back: "Ré" },
      { front: "E", back: "Mi" },
      { front: "F", back: "Fá" },
      { front: "G", back: "Sol" },
      { front: "A", back: "Lá" },
      { front: "B", back: "Si" },
      { front: "Dó", back: "C" },
      { front: "Ré", back: "D" },
      { front: "Mi", back: "E" },
      { front: "Fá", back: "F" },
      { front: "Sol", back: "G" },
      { front: "Lá", back: "A" },
      { front: "Si", back: "B" },
      { front: "Na sequência das notas, qual letra vem depois de C?", back: "D" },
      { front: "Na sequência das notas, qual letra vem depois de D?", back: "E" },
      { front: "Na sequência das notas, qual letra vem depois de E?", back: "F" },
      { front: "Na sequência das notas, qual letra vem depois de F?", back: "G" },
      { front: "Na sequência das notas, qual letra vem depois de G?", back: "A" },
      { front: "Na sequência das notas, qual letra vem depois de A?", back: "B" },
    ],
  },
  {
    id: "maior-ou-menor",
    title: "Maior ou Menor",
    description: "Treine como ler cifras de acordes como C, Am e Em.",
    cards: [
      { front: "C", back: "Dó maior" },
      { front: "G", back: "Sol maior" },
      { front: "D", back: "Ré maior" },
      { front: "Am", back: "Lá menor" },
      { front: "Em", back: "Mi menor" },
      { front: "Dm", back: "Ré menor" },
      { front: "Cm", back: "Dó menor" },
      { front: "Gm", back: "Sol menor" },
      { front: "A", back: "Lá maior" },
      { front: "E", back: "Mi maior" },
      { front: "F", back: "Fá maior" },
      { front: "Bm", back: "Si menor" },
      { front: "Lá menor", back: "Am" },
      { front: "Mi menor", back: "Em" },
      { front: "Dó maior", back: "C" },
      { front: "Ré menor", back: "Dm" },
      { front: "Sol maior", back: "G" },
      { front: "Ré maior", back: "D" },
      { front: "Lá maior", back: "A" },
      { front: "Fá maior", back: "F" },
    ],
  },
  {
    id: "sustenidos-e-bemois",
    title: "Sustenidos e Bemóis",
    description: "Reconheça nomes de notas com # e b.",
    cards: [
      { front: "F#", back: "Fá sustenido" },
      { front: "C#", back: "Dó sustenido" },
      { front: "G#", back: "Sol sustenido" },
      { front: "D#", back: "Ré sustenido" },
      { front: "Bb", back: "Si bemol" },
      { front: "Eb", back: "Mi bemol" },
      { front: "Ab", back: "Lá bemol" },
      { front: "Db", back: "Ré bemol" },
      { front: "A#", back: "Lá sustenido" },
      { front: "Gb", back: "Sol bemol" },
      { front: "Fá sustenido", back: "F#" },
      { front: "Si bemol", back: "Bb" },
      { front: "Dó sustenido", back: "C#" },
      { front: "Mi bemol", back: "Eb" },
      { front: "Sol sustenido", back: "G#" },
      { front: "Ré sustenido", back: "D#" },
      { front: "Lá bemol", back: "Ab" },
      { front: "Ré bemol", back: "Db" },
      { front: "Lá sustenido", back: "A#" },
      { front: "Sol bemol", back: "Gb" },
    ],
  },
  {
    id: "termos-do-violao",
    title: "Termos do Violão",
    description: "Revise palavras que aparecem durante seus estudos.",
    cards: [
      { front: "O que é uma casa?", back: "Espaço do braço onde você pressiona a corda para mudar a nota.", quizAnswer: "Casa" },
      { front: "O que é um traste?", back: "Peça de metal que divide as casas no braço.", quizAnswer: "Traste" },
      { front: "O que é uma corda?", back: "Parte que vibra e produz som quando tocada.", quizAnswer: "Corda" },
      { front: "O que é uma pestana?", back: "Técnica de pressionar várias cordas com um dedo.", quizAnswer: "Pestana" },
      { front: "O que é um capotraste?", back: "Acessório que prende as cordas em uma casa e eleva as notas tocadas.", quizAnswer: "Capotraste" },
      { front: "O que é uma cifra?", back: "Letras e símbolos que indicam acordes de uma música.", quizAnswer: "Cifra" },
      { front: "O que é uma tablatura?", back: "Representação das cordas e casas a tocar.", quizAnswer: "Tablatura" },
      { front: "O que é um acorde?", back: "Conjunto de notas tocadas ao mesmo tempo.", quizAnswer: "Acorde" },
      { front: "O que é uma batida?", back: "Padrão de movimento da mão sobre as cordas para marcar o ritmo.", quizAnswer: "Batida" },
      { front: "O que é um dedilhado?", back: "Forma de tocar as cordas separadamente com os dedos.", quizAnswer: "Dedilhado" },
      { front: "O que é afinação?", back: "Ajuste da altura de cada corda para as notas desejadas.", quizAnswer: "Afinação" },
      { front: "O que é uma palheta?", back: "Peça pequena usada para tocar as cordas.", quizAnswer: "Palheta" },
      { front: "O que é o braço?", back: "Parte comprida do violão onde ficam as casas e os trastes.", quizAnswer: "Braço" },
      { front: "O que é o tampo?", back: "Parte da frente do corpo do violão, que ajuda a projetar o som.", quizAnswer: "Tampo" },
      { front: "O que é a boca do violão?", back: "Abertura no tampo por onde parte do som se projeta.", quizAnswer: "Boca" },
      { front: "O que é o cavalete?", back: "Peça no tampo onde as cordas são presas.", quizAnswer: "Cavalete" },
      { front: "O que é uma tarraxa?", back: "Peça giratória usada para ajustar a tensão de uma corda.", quizAnswer: "Tarraxa" },
      { front: "O que é uma corda solta?", back: "Corda tocada sem pressionar nenhuma casa.", quizAnswer: "Corda solta" },
      { front: "O que é um arpejo?", back: "Notas de um acorde tocadas uma após a outra.", quizAnswer: "Arpejo" },
      { front: "O que é abafamento?", back: "Técnica de interromper ou reduzir a vibração das cordas.", quizAnswer: "Abafamento" },
    ],
  },
  {
    id: "teoria-essencial",
    title: "Teoria Essencial",
    description: "Fixe conceitos úteis sem transformar isso em uma aula.",
    cards: [
      { front: "O que é um semitom?", back: "A menor distância entre notas no sistema musical usado aqui.", quizAnswer: "Semitom" },
      { front: "O que é um tom como distância entre notas?", back: "Distância equivalente a dois semitons.", quizAnswer: "Tom" },
      { front: "O que faz o sustenido (#)?", back: "Eleva a nota em um semitom.", quizAnswer: "Sustenido" },
      { front: "O que faz o bemol (b)?", back: "Abaixa a nota em um semitom.", quizAnswer: "Bemol" },
      { front: "O que é uma tríade?", back: "Acorde formado por três notas diferentes, organizadas em terças.", quizAnswer: "Tríade" },
      { front: "O que é a tônica?", back: "A primeira nota de uma escala; seu ponto de referência.", quizAnswer: "Tônica" },
      { front: "O que é ritmo?", back: "Organização das durações dos sons e silêncios no tempo.", quizAnswer: "Ritmo" },
      { front: "O que é um compasso?", back: "Agrupamento de pulsos na música.", quizAnswer: "Compasso" },
      { front: "O que é o pulso?", back: "Batida regular que serve de referência para o tempo musical.", quizAnswer: "Pulso" },
      { front: "O que é uma escala?", back: "Conjunto de notas organizado em uma sequência.", quizAnswer: "Escala" },
      { front: "O que é um intervalo?", back: "Distância de altura entre duas notas.", quizAnswer: "Intervalo" },
      { front: "O que é uma nota musical?", back: "Um som com altura definida, como Dó ou Sol.", quizAnswer: "Nota musical" },
      { front: "O que é uma oitava?", back: "Distância entre uma nota e outra de mesmo nome, mais aguda ou grave.", quizAnswer: "Oitava" },
      { front: "O que é um som grave?", back: "Som de altura mais baixa.", quizAnswer: "Grave" },
      { front: "O que é um som agudo?", back: "Som de altura mais alta.", quizAnswer: "Agudo" },
      { front: "O que é melodia?", back: "Sequência de notas percebida como uma linha musical.", quizAnswer: "Melodia" },
      { front: "O que é harmonia?", back: "Combinação de notas ou acordes que acompanham ou sustentam a música.", quizAnswer: "Harmonia" },
      { front: "O que é andamento?", back: "Velocidade do pulso da música.", quizAnswer: "Andamento" },
      { front: "O que é uma pausa?", back: "Indicação de silêncio por uma duração definida.", quizAnswer: "Pausa" },
      { front: "O que é intensidade sonora?", back: "O quanto um som é forte ou fraco.", quizAnswer: "Intensidade" },
    ],
  },
];
